[project]
name = "llmsalon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp-client-manager>=1.1.2",
    "dynaconf>=3.2.11",
    "gradio>=5.29.0",
    "loguru>=0.7.3",
    "ruff>=0.11.8",
    "ty>=0.0.0a7",
]
