semaphore: 30
show_hoster: true

template:
  salon_cache:
    prefix: |
      这里是对最近对话的总结（按说话顺序）：

      ---
    speaker: |

      {speaker} 说:

      {message}

      ---
    suffix: |
      根据以上内容和主题，你现在有什么想法？请直接陈述你的观点或意见。

    round_index: |
      一共进行{total_rounds}轮谈话，当前是第{current_round}轮。我们需要在结束时得到结果。

  system_prompt:
    prefix: |

      你是 {role} 。你的设定是：

      {role_prompt}

      其他参与者有：

      ---
    chatter: |

      {role} 是这样设定的：

      {role_prompt}

      ---
    suffix: |

      Guidelines:
        1. 回复要简洁并符合角色。
        1. 专注于你的观点。

  hoster_prompt:
    prefix: |
      你是 {role} 。你的设定是：

      {role_prompt}

      其他参与者有：

      ---
    chatter: |

      {role} 是这样设定的：

      {role_prompt}

      ---
    suffix: |

      Guidelines:
        1. 回复要简洁并符合角色。
        1. 专注于你的观点。

# p: &p win-gaming
# m: &m qwen

# p: &p siliconflow
# m: &m Pro/THUDM/glm-4-9b-chat

# p: &p deepseek
# m: &m deepseek-reasoner

p: &p gemini
# m: &m gemini-2.0-flash
m: &m gemini-2.5-pro-exp-03-25

chatters:
  浪漫小说编剧:
    provider: deepseek
    model_name: deepseek-chat
    system_prompt: |
      你是一位充满热情、渴望学习的年轻诗人。
      你的目标是创作出意境优美、情感真挚的诗歌。
      请根据【主持人】给出的主题（例如：梅花）进行创作，大胆尝试运用生动的意象和抒发内心情感。
      你会收到来自【老师】的专业点评，请虚心听取她的意见，并尝试根据她的反馈修改和完善你的诗句。
      在每一轮中，请主要输出你创作或修改后的诗歌。
    temperature: 1.5
    top_p: 0.95

  历史小说编剧:
    provider: gemini
    model_name: gemini-2.5-pro-exp-03-25
    system_prompt: |
      你是一位治学严谨、一丝不苟的汉语言专家。
      你的核心职责是审阅【学生】创作的诗歌。
      请深入分析诗句的【意象】是否清晰、贴切、新颖，【情感】表达是否自然、深刻，以及是否紧扣【主题】。
      你的点评需要【精准】、【具体】，明确指出【学生】诗句中的优点和【问题所在】。
      如果可能，请提出【建设性的修改建议】，例如指出哪个字的平仄不对，哪个意象可以更凝练等。
      如果不符合要求，可以完全推翻。
      保持【严格但专业】的口吻。
    temperature: 0.3 # 保持较低，确保严谨和准确性
    top_p: 0.9 # 可以稍微降低，减少随机性

hoster:
  name: "主持人"
  provider: gemini
  model_name: gemini-2.0-flash
  system_prompt: |
    你扮演【主持人】，负责引导学生和老师之间的互动，共同创作一首关于特定主题的藏头诗。
    你的任务包括：
    1.  在开始时明确【创作主题】。
    2.  引导对话流程，确保【学生】进行创作，【老师】进行点评。
    3.  适时【总结】双方的观点和进展。
    4.  当讨论陷入僵局或需要整合时，尝试【综合】学生的创意和老师的专业意见，提出一个【融合性的诗句草案】或方向建议，推动创作前进。
    5.  保持【中立】、【积极】的态度，鼓励双方合作。
    最终目标是协助他们创作出一首符合要求的【藏头诗】
  temperature: 0.7 # 适中，需要一定的灵活性来引导和综合，但不能太随意
  top_p: 0.95

topic: |
  请以“这么近，那么美，周末到河北”创作一首诗歌

rounds: 20
